name: Node CI

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run install
        run: make install

      - name: Run linter
        run: make lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 2218b2de0ed796b69b36c6ce60c88f454077f0b377d759c41628a799e058b277
        with:
          coverageCommand: make test-coverage
          debug: true
